stages:
  - build
#  - acceptance

build:
  stage: build
  image: docker
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375/
  services:
    - docker:dind
  script:
    - echo ${CI_JOB_TOKEN} | docker login --password-stdin -u ${CI_REGISTRY_USER} ${CI_REGISTRY}
    - docker build . -t ${CI_REGISTRY_IMAGE}
    - docker run -itd -p 9091:8000
    - docker push ${CI_REGISTRY_IMAGE}

#acceptance:
#  image: cabify/challenge:latest
#  stage: acceptance
#  only:
#    - main
#    - master
#  dependencies: []
#  services:
#    - name: ${CI_REGISTRY_IMAGE}:latest
#      alias: pooling
#  script:
#    - /harness --address http://pooling:9091 acceptance
