stages:
  - build
  - acceptance

build:
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    - echo ${CI_JOB_TOKEN} | docker login --password-stdin -u ${CI_REGISTRY_USER} ${CI_REGISTRY}
    - docker build . -t ${CI_REGISTRY_IMAGE}
    - docker push ${CI_REGISTRY_IMAGE}

acceptance:
  image: cabify/challenge:latest
  stage: acceptance
  only:
    - master
  dependencies: []
  services:
    - name: ${CI_REGISTRY_IMAGE}:latest
      alias: pooling
  script:
    - /harness --address http://pooling:9091 acceptance
