status:
    path: status
    methods: [ GET ]
    defaults:
        _controller: App\CarPooling\Infrastructure\UI\Http\Controller\Status\StatusController

cars:
    path: cars
    methods: [ PUT ]
    defaults:
        _controller: App\CarPooling\Infrastructure\UI\Http\Controller\Car\SetCarFleetController

journey:
    path: journey
    methods: [ PUT ]
    defaults:
        _controller: App\CarPooling\Infrastructure\UI\Http\Controller\Journey\RequestJourneyController

locate:
    path: locate
    methods: [ POST ]
    defaults:
        _controller: App\CarPooling\Infrastructure\UI\Http\Controller\Journey\RequestLocationController

drop_off:
    path: dropoff
    methods: [ POST ]
    defaults:
        _controller: App\CarPooling\Infrastructure\UI\Http\Controller\Journey\RequestDropOffController


