test:
    path: test
    methods: [GET]
    defaults:
        _controller: App\CarPooling\Infrastructure\UI\Http\Controller\TestController

cars:
    path: cars
    methods: [ PUT ]
    defaults:
        _controller: App\CarPooling\Infrastructure\UI\Http\Controller\Cars\PutCarsController


