kernel:
    resource: ../src/Kernel.php
    type: annotation

car_pooling:
    resource: "../src/CarPooling/Infrastructure/Framework/Symfony/Resources/config/routing.yaml"
    defaults:
        _format: json