services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  App\Common\Infrastructure\QueryBus\TacticianQueryBus:
    arguments: [ '@tactician.commandbus' ]

  App\Common\Infrastructure\CommandBus\TacticianCommandBus:
    arguments: [ '@tactician.commandbus' ]

  App\Common\Application\CommandBus\CommandBusInterface: '@App\Common\Infrastructure\CommandBus\TacticianCommandBus'
  App\Common\Application\QueryBus\QueryBusInterface: '@App\Common\Infrastructure\QueryBus\TacticianQueryBus'
